In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('D:\\datafile\\cars_and_careers.csv')
df.head()

      Name Occupation  Age                    Car
0     John   ENGINEER   32           Toyota Camry
1    Emily    TEACHER   28            Honda Civic
2  Michael     DOCTOR   45           Ford Mustang
3     Emma     LAWYER   37           BMW 3 Series
4    David     ARTIST   41  Mercedes-Benz C-Class

In [4]:
df.describe()

             Age
count  20.000000
mean   34.750000
std     5.729655
min    26.000000
25%    29.750000
50%    34.500000
75%    39.250000
max    45.000000

In [5]:
mean_age_df = df['Age'].mean()
mean_age_df

np.float64(34.75)

In [6]:
df_copy = df.copy()
df_copy['Car'] = df_copy['Car'].transform(lambda x: x.capitalize())
df_copy.head()

      Name Occupation  Age                    Car
0     John   ENGINEER   32           Toyota camry
1    Emily    TEACHER   28            Honda civic
2  Michael     DOCTOR   45           Ford mustang
3     Emma     LAWYER   37           Bmw 3 series
4    David     ARTIST   41  Mercedes-benz c-class

In [11]:
df1 = df_copy.shift(periods = 1, axis = 0)
df1.head()

      Name Occupation   Age           Car
0     None       None   NaN          None
1     John   ENGINEER  32.0  Toyota camry
2    Emily    TEACHER  28.0   Honda civic
3  Michael     DOCTOR  45.0  Ford mustang
4     Emma     LAWYER  37.0  Bmw 3 series

In [12]:
df1.iloc[0] = ['Casy', 'Dancer', 31, 'Tesla']
df1.head()

      Name Occupation   Age           Car
0     Casy     Dancer  31.0         Tesla
1     John   ENGINEER  32.0  Toyota camry
2    Emily    TEACHER  28.0   Honda civic
3  Michael     DOCTOR  45.0  Ford mustang
4     Emma     LAWYER  37.0  Bmw 3 series

In [16]:
is_ben = df1['Name'].str.find('Ben') == -len(df1)
is_ben

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Name, dtype: bool

In [18]:
emily_index = df1.index[df1['Name'] == 'Emily'].tolist()

emily_car = df1.loc[emily_index, 'Car']

emily_occupation = df1.loc[emily_index, 'Occupation']

print(f'Emilys car is {emily_car} and occupation is {emily_occupation}')

Emilys car is 2    Honda civic
Name: Car, dtype: object and occupation is 2    TEACHER
Name: Occupation, dtype: object

In [22]:
index_old = df1['Age'].idxmax()
oldest = df1.loc[index_old, 'Car']
oldest

'Ford mustang'